In [6]:
#import libraries
import tensorflow as tf
import numpy

In [2]:
#load and prepare dataset
minist = tf.keras.datasets.mnist


In [3]:
#divide data for train and test
(x_train,y_train),(x_test,y_test) = minist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [4]:
#convert sample from integer to float
x_train,x_test = x_train/255.0 , x_test/255.0

In [5]:
#build the keras.sequential model layer by stacking layer and choose optimizer and loss function

model = tf.keras.Sequential([
                             tf.keras.layers.Flatten(input_shape = (28,28)),
                             tf.keras.layers.Dense(128,activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.12967013, -0.17519394, -0.04334531, -0.15256375, -0.28383964,
        -0.13992439, -0.28292048, -0.09272856, -0.03159475,  0.30577955]],
      dtype=float32)

In [9]:
#The tf.nn.softmax function converts these logits to "probabilities" for each class:

tf.nn.softmax(predictions).numpy()

array([[0.12101228, 0.0892131 , 0.10178641, 0.09125503, 0.08002845,
        0.09241576, 0.08010204, 0.09688196, 0.10298952, 0.14431544]],
      dtype=float32)

In [10]:
#The losses.SparseCategoricalCrossentropy loss takes a vector of logits and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
#This loss is equal to the negative log probability of the true class: It is zero if the model is sure of the correct class.

#This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.



In [12]:
loss_fn(y_train[:1],predictions).numpy()

2.3814578

In [13]:
model.compile(optimizer='adam',loss = loss_fn,metrics=['accuracy'])


In [14]:
#The Model.fit method adjusts the model parameters to minimize the loss:

model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4840 - accuracy: 0.8613
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1498 - accuracy: 0.9557
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1100 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0914 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0748 - accuracy: 0.9761


In [15]:
#The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".

model.evaluate(x_test , y_test ,verbose=2)

313/313 - 0s - loss: 0.0805 - accuracy: 0.9756


[0.0805259570479393, 0.975600004196167]

In [16]:
#The image classifier is now trained to ~98% accuracy on this dataset. 
#If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([
                                         model,tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.62408043e-08, 2.21836371e-09, 5.20990034e-06, 1.86893540e-05,
        1.91546813e-11, 4.47578756e-08, 3.16339348e-13, 9.99973774e-01,
        5.86056217e-07, 1.71340082e-06],
       [1.56598894e-08, 2.41340103e-07, 9.99998927e-01, 8.04041349e-07,
        2.71274337e-18, 9.35595956e-09, 6.31702246e-10, 8.51972084e-13,
        4.81556661e-09, 7.92432079e-17],
       [1.48020554e-04, 9.70579624e-01, 3.00099305e-03, 3.02897824e-04,
        1.14541006e-04, 3.50760420e-05, 3.23378132e-04, 2.47978028e-02,
        6.94786315e-04, 3.00583633e-06],
       [9.99587476e-01, 1.11980283e-08, 3.61107785e-04, 8.83767996e-07,
        6.39519016e-08, 2.57435545e-07, 2.58323257e-06, 2.52533846e-05,
        2.89964870e-08, 2.22189319e-05],
       [3.49128572e-06, 8.70840455e-10, 2.50401513e-06, 3.01137888e-08,
        9.99506474e-01, 2.64073833e-07, 3.08691064e-08, 1.70744504e-04,
        1.31979434e-07, 3.16452672e-04]], dtype=float32)>